### ISSUE TITLE
Can't start Semux on ARM server

### ISSUE THREAD

**Issue by ilya-stepanov** [semuxproject/semux#102]
I have next error when I start semux.sh on ARM server:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni64-1.8 in java.library.path, no leveldbjni-1.8 in java.library.path, no leveldbjni in java.library.path, /tmp/libleveldbjni-64-1-8000972710673745417.8: /tmp/libleveldbjni-64-1-8000972710673745417.8: cannot open shared object file: No such file or directory (Possible cause: architecture word width mismatch)]
    at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
    at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
    at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)
    at org.semux.db.LevelDB.<init>(LevelDB.java:48)
    at org.semux.Kernel$1.<init>(Kernel.java:105)
    at org.semux.Kernel.start(Kernel.java:104)
    at org.semux.CLI.startKernel(CLI.java:149)
    at org.semux.CLI.main(CLI.java:39)
    at org.semux.Semux.main(Semux.java:13)
```

**Comment by semuxproject** [comment]
We won't fix this issue, but community efforts are welcome
