### ISSUE TITLE
Wallet crashed after unexpected system reboot

### ISSUE THREAD

**Issue by ilya-stepanov** [semuxproject/semux#24]
I faced with error when my pc unexpectedly rebooted and after reboot I could not start the wallet.

Here is the console output:
```
09/20 01:38:01 [main] INFO Config - System booting up: network = 1, coinbase = 6455e135af45bec5bd3572d6e3b5c42e9ef92870
Exception in thread "main" java.lang.NullPointerException
        at org.semux.core.BlockchainImpl.getLatestBlockNumber(BlockchainImpl.java:100)
        at org.semux.Kernel.start(Kernel.java:134)
        at org.semux.GUI.showMain(GUI.java:127)
        at org.semux.GUI.main(GUI.java:78)
        at org.semux.Semux.main(Semux.java:15)
```

The issue was fixed for me when I download again the latest version and re-sync everything.

**Comment by semuxproject** [comment]
This is due to data corruption. This only solution for is re-sync
