### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by semuxproject** [semuxproject/semux#243]
As reported by leoirssi

```
1/16 17:59:29 [cons] INFO SemuxBFT - Block [number = 23309, view = 0, hash = c3a2140be886ff933d9e2cb77753d23b49321ebbbdcc94ccc9d71f27ba192d9d, # txs = 0, # votes = 55]
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
    at sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:148)
    at sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:356)
    at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
    at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
    at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
    at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1014)
    at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
    at sun.awt.image.ImageRepresentation.drawToBufImage(ImageRepresentation.java:813)
    at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1021)
    at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186)
    at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
    at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296)
    at javax.swing.ImageIcon.paintIcon(ImageIcon.java:425)
    at javax.swing.plaf.basic.BasicLabelUI.paint(BasicLabelUI.java:167)
    at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
    at javax.swing.JComponent.paintComponent(JComponent.java:780)
    at javax.swing.JComponent.paint(JComponent.java:1056)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
    at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
    at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
```

**Comment by semuxproject** [comment]
This is a JDK bug, https://bugs.openjdk.java.net/browse/JDK-7172749
