### ISSUE TITLE
ERROR Message: Failed to retrieve your IP address

### ISSUE THREAD

**Issue by MeazZa** [semuxproject/semux#336]
Hi dev,

- Question Description

An error occurs when i trying to synchronize the data, the debug log likes this:
```
2017-12-17 14:41:23 [client-0] INFO  PeerClient - Noticed IP change: 118.144.140.252 => 192.168.15.1
2017-12-17 14:41:53 [client-0] INFO  PeerClient - Noticed IP change: 192.168.15.1 => 118.144.140.252
2017-12-17 14:43:37 [client-10] INFO  SemuxP2pHandler - Received DISCONNECT msg, reason = INVALID_HANDSHAKE
2017-12-17 14:43:40 [client-9] INFO  SemuxP2pHandler - Received DISCONNECT msg, reason = INVALID_HANDSHAKE
2017-12-17 14:43:40 [client-8] INFO  SemuxP2pHandler - Received DISCONNECT msg, reason = INVALID_HANDSHAKE
2017-12-17 14:43:41 [client-7] INFO  SemuxP2pHandler - Received DISCONNECT msg, reason = INVALID_HANDSHAKE
2017-12-17 14:44:53 [client-0] ERROR SystemUtil - Failed to retrieve your IP address
java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at org.semux.util.SystemUtil.getIp(SystemUtil.java:92)
	at org.semux.net.PeerClient.lambda$startIpRefresh$0(PeerClient.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

- Here is my software information:

Semux version: `v1.0.0-rc.4`
OS & Version: `Windows 10

i'm glad to provide any information you needed

Best
Regards

**Comment by semuxproject** [comment]
With a recent switch to OpenDNS, we will see which provider is more stable.

**Comment by semuxproject** [comment]
Fixed, to be included
