### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by jezzmemo** [semuxproject/semux#353]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the Discord channel here: https://discord.gg/qQVckKZ

#### System information

Semux version: `1.0.0-rc.4`

OS & Version: `semux-macos`

#### Expected behaviour

None

#### Steps to reproduce the behaviour

1. Step one
Open application
2. Step two
Launch a few minutes

#### Backtrace

````
Exception in thread "gui-data" Exception in thread "msg-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.addWaiter(AbstractQueuedSynchronizer.java:606)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.offer(ScheduledThreadPoolExecutor.java:1010)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.add(ScheduledThreadPoolExecutor.java:1037)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.add(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ScheduledThreadPoolExecutor.reExecutePeriodic(ScheduledThreadPoolExecutor.java:346)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:296)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pending-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
````

**Comment by semuxproject** [comment]
What's your system configuration, especially memory size?

**Comment by jezzmemo** [comment]
MAC OS X 10.12.6 
8 GB 2133 MHz LPDDR3
