### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by jezzmemo** [semuxproject/semux#390]
Hi there,

#### System information

Semux version: `semux-macos-1.0.0-rc.5`

OS & Version: `macOS 10.12.6`

#### Steps to reproduce the behaviour

1.open the wallet application
2.click the wallet action menu
3.click restore from the backup menu item
4.choose the xxx.xxx folder will occur this bug

#### Backtrace

````
java.io.FileNotFoundException: /Users/xxx/Desktop/xxx.app (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.semux.util.IOUtil.readFile(IOUtil.java:70)
	at org.semux.core.Wallet.unlock(Wallet.java:96)
	at org.semux.gui.MenuBar.recoverAccounts(MenuBar.java:146)
	at org.semux.gui.MenuBar.actionPerformed(MenuBar.java:105)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
````

**Comment by semuxproject** [comment]
Could you describe the steps to reproduce it?

**Comment by jezzmemo** [comment]
@semuxproject 
reproduce steps:
1.open the wallet application
2.click the wallet action menu
3.click restore from the backup menu item
4.choose the xxx.xxx folder will occur this bug

**Comment by semuxproject** [comment]
Tried to reproduce it but unable to select a folder on macOS (the `FileChooser` has the `.data` file type filter).

Anyway, this won't cause substantial issues except creating a log.

**Comment by jezzmemo** [comment]
@semuxproject 
It is possible xxx.xxx is the folder, you have to check whether this folder, I tested the results of your filter problems, otherwise this exception does not appear, follow-up you have time to remember to fix
