### ISSUE TITLE
org.iq80.leveldb.DBException: Closed

### ISSUE THREAD

**Issue by jezzmemo** [semuxproject/semux#418]
Hi there,

#### System information

Semux version: `semux-macos-1.0.0-rc.5`

OS & Version: `macOS 10.12.6`

#### Expected behaviour

Normal close application

#### Actual behaviour

When application syncing block,I close the application,the console show exception info

#### Steps to reproduce the behaviour

1. When semux syncing block
2. Close the semux application
#### Backtrace

````
376fe55ebc5e378509cd12e87e3e2e218a258ff2fb, # txs = 0, # votes = 62]
23:21:33.636 [INFO]   SemuxSync        Block [number = 49694, view = 0, hash = 74f707dd16f7171138249559f336184a7243a7b35668e7ada5b2172b40260160, # txs = 0, # votes = 58]
23:21:33.654 [INFO]   SemuxSync        Block [number = 49695, view = 0, hash = aaa8ee7e6f53023492cf109a27f6234631c166c5092f09f9e684912361a146f8, # txs = 0, # votes = 61]
23:21:33.674 [INFO]   SemuxSync        Block [number = 49696, view = 0, hash = 9cba8676ee0b944e181b88095d575c576022e4c07708d1120a0e2dcec7ec1578, # txs = 0, # votes = 58]
23:21:33.691 [INFO]   SemuxSync        Block [number = 49697, view = 0, hash = 55734b545113861e8d82a678e77f39386bd4998e2378542ea63f3bb159c245de, # txs = 0, # votes = 61]
^C23:21:36.227 [INFO]   Kernel           Shutting down GUI
23:21:36.233 [INFO]   SemuxGUI         Data refresh interrupted, exiting
23:21:36.238 [INFO]   SemuxSync        Syncing finished, took 00:10:45
23:21:36.238 [INFO]   SemuxBFT         Consensus stopped
23:21:36.248 [INFO]   PeerServer       PeerServer shut down
23:21:36.249 [INFO]   NodeManager      Node manager stopped
23:21:36.249 [INFO]   PeerClient       Shutting down PeerClient
Exception in thread "AWT-EventQueue-0" org.iq80.leveldb.DBException: Closed
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:75)
	at org.semux.db.LevelDB.get(LevelDB.java:118)
	at org.semux.core.BlockchainImpl.getValidatorStats(BlockchainImpl.java:367)
	at org.semux.gui.panel.DelegatesPanel.refreshDelegates(DelegatesPanel.java:421)
	at org.semux.gui.panel.DelegatesPanel.actionPerformed(DelegatesPanel.java:355)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1332)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:131)
	at javax.swing.JComboBox.addItem(JComboBox.java:716)
	at org.semux.gui.panel.DelegatesPanel.refreshAccounts(DelegatesPanel.java:386)
	at org.semux.gui.panel.DelegatesPanel.actionPerformed(DelegatesPanel.java:351)
	at org.semux.gui.model.WalletModel.lambda$updateView$0(WalletModel.java:215)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
````

My addresss is:0x2d69998d2050faca6777cee82e7d9f6b1cc372bb.
Thank you.

**Comment by semuxproject** [comment]
The GUI is still accessing the state when the kernel is closed. Need more investigation

**Comment by jezzmemo** [comment]
@semuxproject So you must cancel all the task,and the close the kernel resource
