### ISSUE TITLE
[develop]  ArrayIndexOutOfBounds on recieving disconnect (empty Frame)

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#425]
#### System information

Semux version: 1.0.0 (Develop branch)

OS & Version: OSX

Commit hash : tested on 5fc0fdd

#### Expected behaviour

If the client receives a Bad/Empty frame, it should be parsed appropriately, and not spam logs if reason code is not set.  If there is an errant peer sending bad data, we should not cause all other clients to spam logs.

It seems like empty Frame objects are being parsed as a Disconnect message with no reason set.

**this appears to be due to commit d53f2cb0 - Net: refactor the framing protocol
Bad/empty frames are not ignored**

#### Actual behaviour

This appears to be from getting an empty frame object

<img width="582" alt="screen shot 2018-01-04 at 9 22 02 pm" src="https://user-images.githubusercontent.com/24282143/34596529-6abd1f02-f195-11e7-8632-b653e36e9686.png">

This causes the code to process it as a Disconnect (0 is same as unset)
But there appears to be no message data attached.  Error should be handled better/suppressed for a disconnect or badly formed message.

```
20:55:06.098 [WARN]   MessageFactory   Failed to parse encoded message data
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.semux.util.Bytes.toByte(Bytes.java:229)
	at org.semux.net.msg.p2p.DisconnectMessage.<init>(DisconnectMessage.java:41)
	at org.semux.net.msg.MessageFactory.create(MessageFactory.java:48)
	at org.semux.net.SemuxMessageHandler.decodeMessage(SemuxMessageHandler.java:144)
	at org.semux.net.SemuxMessageHandler.decode(SemuxMessageHandler.java:110)
	at org.semux.net.SemuxMessageHandler.decode(SemuxMessageHandler.java:28)
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.ByteToMessageCodec.channelInactive(ByteToMessageCodec.java:118)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

#### Steps to reproduce the behaviour

1. Connect to test network with latest branch
2. Get 1000s of above stack trace.

or
1. Fire an empty Frame message

It does eventually resolve itself, then only to happen again.

It seems like adding something like 
```
  if(frame.getPacketSize() == 0)
        {
            return;
        }
```
to SemuxFrameHandler.decode() or some other similiar check would fix the issue, but I'm not sure of all the different packet varieties.

0x5c0c8a67ee6c14fa853c4595cd90e57359efe589

**Comment by semuxproject** [comment]
I didn't receive any error logs like this, but I believe it's possible.

Needs more thoughts on whether empty message (encoded into a single frame with `packetSize = 0`) should be allowed.

One thing for sure is that we need to change the level of some network messages to DEBUG.

**Comment by orogvany** [comment]
I'm good either way as long as they don't spam my logs 100s of times per minute :D

**Comment by semuxproject** [comment]
The connection should be dropped after an exception. Are you experiencing this constantly? 

Possible to debug a little bit?

**Comment by orogvany** [comment]
Yes, I get this constantly.  I'll spend a little time and see if it's just one peer, or what's going on.

**Comment by orogvany** [comment]
Might be an off by one.
I see this only when SemuxFrameHandler:63 returns a readerIndex of 16

It wants to read the next Frame, but there's just 0's for all the things it tries to read, so the frame has 0 for all values.
