### ISSUE TITLE
Can't open the wallet after entering correct password

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#524]
#### System information

Semux version: v1.0.0.0

OS & Version: Windows 10 64 bit

Java Runtime: Version 8 Update 161

#### Expected behaviour

User should be able to see wallet after login.

#### Actual behaviour

I see Error popup with this message: input [0, 0], require: [0, 4]

2018-01-20T21:09:57-0500 ERROR    SemuxGui         Uncaught exception during kernel startup.
java.lang.IndexOutOfBoundsException: input [0, 0], require: [0 4]
	at org.semux.util.SimpleDecoder.require(SimpleDecoder.java:117) ~[semux.exe:4a83a2d]
	at org.semux.util.SimpleDecoder.readInt(SimpleDecoder.java:52) ~[semux.exe:4a83a2d]
	at org.semux.util.SimpleDecoder.readLong(SimpleDecoder.java:57) ~[semux.exe:4a83a2d]
	at org.semux.core.BlockHeader.<init>(BlockHeader.java:89) ~[semux.exe:4a83a2d]
	at org.semux.core.BlockHeader.fromBytes(BlockHeader.java:168) ~[semux.exe:4a83a2d]
	at org.semux.core.Block.fromBytes(Block.java:390) ~[semux.exe:4a83a2d]
	at org.semux.core.BlockchainImpl.getBlock(BlockchainImpl.java:167) ~[semux.exe:4a83a2d]
	at org.semux.core.BlockchainImpl.<init>(BlockchainImpl.java:125) ~[semux.exe:4a83a2d]
	at org.semux.Kernel.start(Kernel.java:129) ~[semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:240) ~[semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:214) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.showUnlock(SemuxGui.java:179) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:143) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:81) [semux.exe:4a83a2d]

#### Steps to reproduce the behaviour
1. Update Java Runtime to latest 161 version
2. Update Semux wallet to version 1.0.0.0
3. Start app and enter correct password
4. See the error message

**Comment by cryptokat** [comment]
Could you attach your `debug.log` file?

**Comment by semuxproject** [comment]
Also, try exporting your private key via the old wallet. Be sure to copy your wallet file

**Comment by cryptokat** [comment]
This is due to opening the beta version of database from 1.0.0. The issue can be resolved by deleting your `database` folder.

**Comment by aocolitii** [comment]
I don't like the idea of deleting Database folder. This is no a resolution. I have to re-sync the whole database again. I don't have an old wallet. I just downloaded new version and copy & pasted on top of previous one. Wallet.data file is there. Maybe there is a command that I can run from command file in order to fix database/index?

**Comment by aocolitii** [comment]
Do you have an already synced to latest database that can be downloaded in one click? So I can download it and just replace broken one. This is what NEO did for their GUI wallet.

**Comment by cryptokat** [comment]
@aocolitii The latest block number is 1596 now. It will only take a few minutes to sync with the network.

**Comment by aocolitii** [comment]
@cryptokat done. looks good. it took less then 1 minute to sync. Btw, are you still paying for bounty program? I sent to an email several days ago, no reply. I will just copy body here:

Hi Semux Team,

I have filed around 15-20 bugs and feature request for your project.
Is your bug bounty program still open?

If so, please can you send me the reward for dedicating my personal time for finding these bugs.

Thank you.

**Comment by sider123** [comment]
Thank you for your reply. I updated the latest wallet software yesterday. It's all right now. @cryptokat
