### ISSUE TITLE
address book not work

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#552]
Hi there,

#### System information

Semux version: v1.0.0-rc.1

OS & Version: Windows 10

#### Expected behaviour

show address book

#### Actual behaviour

show noting

#### Steps to reproduce the behaviour

1. click “send” tab
2. click “address book”

#### Backtrace

````
[backtrace]
````

**Comment by likaigithub** [comment]
FYI，there is error stack：

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Name can't be null or empty
	at org.semux.gui.AddressBookEntry.<init>(AddressBookEntry.java:27)
	at org.semux.gui.dialog.AddressBookDialog.getAddressBookEntries(AddressBookDialog.java:235)
	at org.semux.gui.dialog.AddressBookDialog.refresh(AddressBookDialog.java:212)
	at org.semux.gui.dialog.AddressBookDialog.<init>(AddressBookDialog.java:96)
	at org.semux.gui.panel.SendPanel.showAddressBook(SendPanel.java:406)
	at org.semux.gui.panel.SendPanel.actionPerformed(SendPanel.java:284)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by semuxdev** [comment]
You can put pretty much any alias in wallet, based on https://github.com/semuxproject/semux/blob/4a83a2d527f5fe87e6a311d56faced96341d1230/src/main/java/org/semux/core/Wallet.java#L484-L488

However, it's not allowed here https://github.com/semuxproject/semux/blob/4a83a2d527f5fe87e6a311d56faced96341d1230/src/main/java/org/semux/gui/AddressBookEntry.java#L25-L34

**Comment by likaigithub** [comment]
Hi,dev,i want to konw how to earn the Bug bounties.

**Comment by likaigithub** [comment]
If you find this helpful, this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by cryptokat** [comment]
This should no longer be reproducible as we've removed the support of addressbook.json
