### ISSUE TITLE
Data Base corruption on PC power loss

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#58]
Client won't sync after unexpected power loss. 
database folder removal and re-sync from zero fixes the issue. 

DEBUG SemuxSync - Invalid transaction
INFO SemuxSync - Invalid block
DEBUG SemuxP2pHandler - Exception in P2P handler, cid = 56
java.io.IOException: An existing connection was forcibly closed by the remote host

Attached screenshot and txt example of the errors. 

![image](https://user-images.githubusercontent.com/32023262/31532736-bff7617e-aff7-11e7-9e2b-668625ba385b.png)

```
10/13 09:11:11 [sync-mgr-0] DEBUG SemuxSync - Downloading of block #31339 has expired
10/13 09:11:11 [sync-mgr-0] DEBUG SemuxSync - Request block #31339 from cid = 79
10/13 09:11:25 [sync-mgr-0] INFO SemuxSync - Block [number = 31339, view = 0, hash = b4f03f0fdf4bd55681b3150eb3d72fbfee1c5a3ff74f027b3a7d6b1feb2cac3c, # txs = 2643, # votes = 35]
10/13 09:11:25 [sync-mgr-0] DEBUG SemuxSync - Invalid transaction: type = TRANSFER, hash = b0da34acef098e506fe3624aa924693d2402b387bbf5d9c0da6b3713f152b424
10/13 09:11:25 [sync-mgr-0] INFO SemuxSync - Invalid block
10/13 09:11:26 [sync-mgr-0] DEBUG SemuxSync - Request block #31339 from cid = 63
10/13 09:11:27 [p2p-server-4] DEBUG SemuxP2pHandler - Exception in P2P handler, cid = 56
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Unknown Source)
10/13 09:11:27 [p2p-server-4] DEBUG ChannelManager - Channel removed: remoteAddress = 95.81.205.199:57713
10/13 09:11:27 [p2p-server-4] DEBUG SemuxP2pHandler - P2P handler inactive, cid = 56
10/13 09:11:27 [p2p-server-7] DEBUG SemuxChannelInitializer - New inbound channel: remoteAddress = 1.52.39.190:43629
10/13 09:11:27 [p2p-server-7] DEBUG ChannelManager - Channel added: remoteAddress = 1.52.39.190:43629
10/13 09:11:27 [p2p-server-7] DEBUG SemuxP2pHandler - P2P handler active, cid = 85
10/13 09:11:30 [p2p-client-7] DEBUG ChannelManager - Channel removed: remoteAddress = 95.81.205.199:5161
10/13 09:11:30 [p2p-client-7] DEBUG SemuxP2pHandler - P2P handler inactive, cid = 22
```

**Comment by semuxproject** [comment]
TODO: add database integrity check and re-sync feature
