### ISSUE TITLE
the wallet can not launch

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#584]
Hi there,

#### System information

Semux version: v1.0.0-rc.1

OS & Version:  Windows 10

#### Expected behaviour

launch the wallet

#### Actual behaviour
the wallet can not launch

#### Steps to reproduce the behaviour

1. put the wallet in a path with chinese characters.
2. click semux.exe.

#### Backtrace

If you find this helpful, this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by likaigithub** [comment]
FYI,  this is  debug.log

2018-01-26T10:18:26+0800 ERROR    LevelDb          Failed to open database
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\Users\bei\Desktop\新建文件夿 (2)\semux-windows-1.0.0-4a83a2d\semux-windows-1.0.0-4a83a2d\database\index\LOCK: Could not lock file.
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168) ~[semux.exe:4a83a2d]
	at org.semux.db.LevelDb.open(LevelDb.java:78) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb.<init>(LevelDb.java:49) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.open(LevelDb.java:226) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.<init>(LevelDb.java:218) [semux.exe:4a83a2d]
	at org.semux.Kernel.start(Kernel.java:128) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:240) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:214) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.showWelcome(SemuxGui.java:159) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:141) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:81) [semux.exe:4a83a2d]
2018-01-26T10:18:26+0800 ERROR    LevelDb          Failed to open database
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\Users\bei\Desktop\新建文件夿 (2)\semux-windows-1.0.0-4a83a2d\semux-windows-1.0.0-4a83a2d\database\block\LOCK: Could not lock file.
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168) ~[semux.exe:4a83a2d]
	at org.semux.db.LevelDb.open(LevelDb.java:78) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb.<init>(LevelDb.java:49) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.open(LevelDb.java:226) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.<init>(LevelDb.java:218) [semux.exe:4a83a2d]
	at org.semux.Kernel.start(Kernel.java:128) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:240) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:214) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.showWelcome(SemuxGui.java:159) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:141) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:81) [semux.exe:4a83a2d]
2018-01-26T10:18:26+0800 ERROR    LevelDb          Failed to open database
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\Users\bei\Desktop\新建文件夿 (2)\semux-windows-1.0.0-4a83a2d\semux-windows-1.0.0-4a83a2d\database\account\LOCK: Could not lock file.
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168) ~[semux.exe:4a83a2d]
	at org.semux.db.LevelDb.open(LevelDb.java:78) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb.<init>(LevelDb.java:49) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.open(LevelDb.java:226) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.<init>(LevelDb.java:218) [semux.exe:4a83a2d]
	at org.semux.Kernel.start(Kernel.java:128) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:240) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:214) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.showWelcome(SemuxGui.java:159) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:141) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:81) [semux.exe:4a83a2d]
2018-01-26T10:18:26+0800 ERROR    LevelDb          Failed to open database
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\Users\bei\Desktop\新建文件夿 (2)\semux-windows-1.0.0-4a83a2d\semux-windows-1.0.0-4a83a2d\database\delegate\LOCK: Could not lock file.
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168) ~[semux.exe:4a83a2d]
	at org.semux.db.LevelDb.open(LevelDb.java:78) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb.<init>(LevelDb.java:49) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.open(LevelDb.java:226) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.<init>(LevelDb.java:218) [semux.exe:4a83a2d]
	at org.semux.Kernel.start(Kernel.java:128) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:240) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:214) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.showWelcome(SemuxGui.java:159) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:141) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:81) [semux.exe:4a83a2d]
2018-01-26T10:18:26+0800 ERROR    LevelDb          Failed to open database
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\Users\bei\Desktop\新建文件夿 (2)\semux-windows-1.0.0-4a83a2d\semux-windows-1.0.0-4a83a2d\database\vote\LOCK: Could not lock file.
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168) ~[semux.exe:4a83a2d]
	at org.semux.db.LevelDb.open(LevelDb.java:78) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb.<init>(LevelDb.java:49) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.open(LevelDb.java:226) [semux.exe:4a83a2d]
	at org.semux.db.LevelDb$LevelDbFactory.<init>(LevelDb.java:218) [semux.exe:4a83a2d]
	at org.semux.Kernel.start(Kernel.java:128) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:240) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:214) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.showWelcome(SemuxGui.java:159) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:141) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:81) [semux.exe:4a83a2d]

**Comment by semuxdev** [comment]
You have another semux instance running at the same time? Looks like the database lock is hold by another process

**Comment by cryptokat** [comment]
related: #305
