### ISSUE TITLE
IO error : Could not create random access file

### ISSUE THREAD

**Issue by JaviAnaibarro** [semuxproject/semux#649]
#### System information

Semux version: `e.g., v1.0.0-rc.1`

OS & Version: `e.g., Windows 7

#### Expected behaviour

Running the wallet

#### Actual behaviour

Wallet did not run and error.
It run if i restarted it but after i closed it for a few hours it appeared again.

#### Steps to reproduce the behaviour

1. Run the wallet
2.Run > Close > Wait for a hour/s > Run > Error

#### Backtrace
```
 INFO     NodeManager      Node manager started
2018-02-08T15:16:30+0700 INFO     PeerServer       Starting peer server: address = 0.0.0.0:5161
2018-02-08T15:16:31+0700 INFO     SemuxBft         Consensus started
2018-02-08T15:16:31+0700 INFO     SemuxBft         Entered new_height: height = 48785, # validators = 100
2018-02-08T15:16:31+0700 INFO     PeerClient       New IP address detected: 127.0.0.1 => 27.121.85.254
2018-02-08T15:16:33+0700 INFO     Kernel           Found a gateway device: local address = 192.168.0.101, external address = 192.168.1.5
2018-02-08T15:16:37+0700 INFO     SemuxSync        Syncing started, best known block = 50932
2018-02-08T15:16:42+0700 INFO     SemuxP2pHandler  Received DISCONNECT message: reason = TOO_MANY_PEERS, remoteIP = 52.56.196.173
2018-02-08T15:16:43+0700 ERROR    SemuxGui         Uncaught exception during kernel startup.
org.iq80.leveldb.DBException: IO error: C:\Users\ASUS ROG\Downloads\Jangan Dihapus\semux-windows-1.0.0-4a83a2d\database\index\000264.sst: Could not create random access file.
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:90) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:77) ~[semux.exe:4a83a2d]
	at org.semux.db.LevelDb.get(LevelDb.java:118) ~[semux.exe:4a83a2d]
	at org.semux.core.BlockchainImpl.getValidators(BlockchainImpl.java:367) ~[semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.processBlock(SemuxGui.java:344) ~[semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:243) ~[semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:214) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.showUnlock(SemuxGui.java:179) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:143) [semux.exe:4a83a2d]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:81) [semux.exe:4a83a2d]
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\Users\ASUS ROG\Downloads\Jangan Dihapus\semux-windows-1.0.0-4a83a2d\database\index\000264.sst: Could not create random access file.
	at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:316) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:300) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:293) ~[semux.exe:4a83a2d]
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:85) ~[semux.exe:4a83a2d]
	... 9 more
```

**Comment by cryptokat** [comment]
This could be due to: https://github.com/fusesource/leveldbjni/issues/28

**Comment by JaviAnaibarro** [comment]
and now i can not run the wallet completely,
(need to delete the database and resync from the beginning,to run the wallet)
also some people got the same problem like i did.

**Comment by Inon-zhang** [comment]
#683 Can you help me to answer this question?

**Comment by cryptokat** [comment]
Hi @JaviAnaibarro 
Could you provide the architecture of your Windows? (32-bit or 64-bit)

**Comment by JaviAnaibarro** [comment]
@cryptokat It's 64-bit
