### ISSUE TITLE
Windows 7 x86 can't find libraries

### ISSUE THREAD

**Issue by JetP1L0t** [semuxproject/semux#66]
Fresh install on Win7 x86 + JRE 8u144 getting error after "Create new wallet" window:
It doesn't matter if I create new wallet or import old. If I create wallet before i got password dialog and then same exception:
```
10/16 00:40:36 [main] INFO Config - Semux v1.0.0-beta.4
10/16 00:40:36 [main] INFO Config - System booting up: network = 0, coinbase = d
6696903b04549b0adfebe4a65d5923a72c7f8c2
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load librar
y. Reasons: [no leveldbjni32-1.8 in java.library.path, no leveldbjni-1.8 in java
.library.path, no leveldbjni in java.library.path, C:\Temp\leveldbjni-32-1-22650
38472477693022.8: Can't find dependent libraries]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)

        at org.semux.db.LevelDB.<init>(LevelDB.java:48)
        at org.semux.Kernel$1.<init>(Kernel.java:105)
        at org.semux.Kernel.start(Kernel.java:104)
        at org.semux.GUI.showMain(GUI.java:130)
        at org.semux.GUI.main(GUI.java:81)
        at org.semux.Semux.main(Semux.java:15)
```

**Comment by semuxproject** [comment]
Did you install Microsoft Visual C++ 2010 Redistributable Package?
 - [32-bit](http://www.microsoft.com/en-us/download/details.aspx?id=5555)
 - [64-bit](https://www.microsoft.com/en-us/download/details.aspx?id=14632)

**Comment by JetP1L0t** [comment]
Yep, I do. I've got 2005, 2008, 2010, 2013 VC redistributable installed with all msvcp*.dll in %system32%. I'll try to check it's integrity or reinstall and write back later. Maybe some additional suggestions?

**Comment by semuxproject** [comment]
Unable to reproduce this issue on Windows 7 x86.
