### ISSUE TITLE
API fails to handle POST requests

### ISSUE THREAD

**Issue by IJane** [semuxproject/semux#67]
POST requests to the API are failing with "curl: (52) Empty reply from server" while GET requests are fine.

```
[api-server-7] DEBUG SemuxHttpHandler - Exception in API http handler
java.lang.IndexOutOfBoundsException: readerIndex(0) + length(524288) exceeds writerIndex(46): PooledSlicedByteBuf(ridx: 0, widx: 46, cap: 46/46, unwrapped: PooledUnsafeDirectByteBuf(ridx: 177, widx: 177, cap: 1024))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:881)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:874)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:864)
        at org.semux.api.SemuxHttpHandler.channelRead0(SemuxHttpHandler.java:93)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)

```

**Comment by honeycrypto** [comment]
@IJane API shouldn't handle POST/PUT/.. requests in this case.

**Comment by semuxproject** [comment]
Both GET and POST requests are widely used, and should therefore be supported.

**Comment by semuxproject** [comment]
Fixed in the master branch, to be included in next release.
