### ISSUE TITLE
Validator stuck

### ISSUE THREAD

**Issue by Messier81z** [semuxproject/semux#672]
#### System information

Semux version:  Semux/v1.0.0-4a83a2d/Linux/amd64

OS & Version: Ubuntu 16.04

Validator running in the cli mode in foreground (semux-cli.sh) got stuck at height 80163 for several hours. The process was then closed with Ctrl-C and restarted with the same command ./semux-cli.sh which returned a leveldb exception. I then discovered that although I closed the parent process with Ctrl-C a child process was still running detached (seen below as the output of the ps aux command). Killing the process didn't work until issuing kill -9. After that I restarted the ./semux-cli.sh which this time started syncing blocks.

#### Backtrace

1) End of debug.log as when the semux process got stuck:

2018-02-19T03:02:36+0100 INFO     SemuxBft         Entered new_height: height = 80163, # validators = 100
2018-02-19T03:02:39+0100 INFO     SemuxBft         Entered propose: height = 80163, view = 0, primary = false, # connected validators = 1 + 92
2018-02-19T03:02:52+0100 INFO     SemuxBft         Entered validate: proposal = true, votes = [26, 0] [0, 0] [0, 0]
2018-02-19T03:03:00+0100 INFO     SemuxBft         Entered pre_commit: proposal = true, votes = [92, 0] [73, 0] [0, 0]
2018-02-19T03:03:05+0100 INFO     SemuxBft         Entered finalize: proposal = true, votes = [92, 4] [92, 0] [67, 0]
2018-02-19T03:03:05+0100 INFO     SemuxBft         Block [number = 80163, view = 0, hash = 35ae7f5f215ec20e66d426dc4165580bf19016f84a22dcd726d36505c1005cbe, # txs = 0, # votes = 92]
2018-02-19T03:03:07+0100 INFO     SemuxSync        Syncing started, best known block = 80163

2) Ctrl-C on the running semux.cli.sh, it exits; got the command prompt back in the terminal.
3) run ./semux-cli.sh, returns error:

semux-linux-1.0.0-4a83a2d$ ./semux-cli.sh 
Please enter your password: 
16:53:04.675 INFO     Kernel           Semux/v1.0.0-4a83a2d/Linux/amd64
16:53:04.697 INFO     Kernel           System booting up: network = mainnet, networkVersion = 0, coinbase = xxx
16:53:04.939 INFO     Kernel           Computer: manufacturer = VMware, Inc., model = VMware Virtual Platform
16:53:05.060 INFO     Kernel           OS: name = GNU/Linux Ubuntu 16.04.3 LTS (Xenial Xerus) build 4.4.0-112-generic
16:53:05.080 INFO     Kernel           CPU: processor = Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz, cores = 2 / 2
16:53:05.083 INFO     Kernel           Memory: total = 3947 MB, available = 2211 MB, swap total = 5047 MB, swap available = 5038 MB
16:53:05.190 INFO     Kernel           Disk: name = /dev/sr0, size = 1023 MB
16:53:05.191 INFO     Kernel           Disk: name = /dev/sda, size = 81920 MB
16:53:05.193 INFO     Kernel           Disk: name = /dev/fd0, size = 0 MB
16:53:05.194 INFO     Kernel           Disk: name = /dev/dm-0, size = 39528 MB
16:53:05.195 INFO     Kernel           Disk: name = /dev/dm-1, size = 952 MB
16:53:05.212 INFO     Kernel           Network: name = eth0, ip = [xxx]
16:53:05.214 INFO     Kernel           Java: version = 1.8.0_161, xmx = 1618 MB
16:53:05.279 ERROR    LevelDb          Failed to open database
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/semux/semux-linux-1.0.0-4a83a2d/database/index/LOCK: Resource temporarily unavailable
        at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[semux.jar:4a83a2d]
        at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218) ~[semux.jar:4a83a2d]
        at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168) ~[semux.jar:4a83a2d]
        at org.semux.db.LevelDb.open(LevelDb.java:78) [semux.jar:4a83a2d]
        at org.semux.db.LevelDb.<init>(LevelDb.java:49) [semux.jar:4a83a2d]
        at org.semux.db.LevelDb$LevelDbFactory.open(LevelDb.java:226) [semux.jar:4a83a2d]
        at org.semux.db.LevelDb$LevelDbFactory.<init>(LevelDb.java:218) [semux.jar:4a83a2d]
        at org.semux.Kernel.start(Kernel.java:128) [semux.jar:4a83a2d]
        at org.semux.cli.SemuxCli.startKernel(SemuxCli.java:183) [semux.jar:4a83a2d]
        at org.semux.cli.SemuxCli.start(SemuxCli.java:174) [semux.jar:4a83a2d]
        at org.semux.cli.SemuxCli.start(SemuxCli.java:136) [semux.jar:4a83a2d]
        at org.semux.cli.SemuxCli.main(SemuxCli.java:43) [semux.jar:4a83a2d]

4) ps aux | grep semux
semux    18884 72.7 39.4 6023112 1594352 pts/2 Sl   Feb01 18808:06 /usr/lib/jvm/java-8-oracle/jre/bin/java -cp semux.jar -Xmx2752M -Dlog4j2.garbagefreeThreadContextMap=true -Dlog4j2.shutdownHookEnabled=false -Dlog4j2.disableJmx=true org.semux.cli.SemuxCli

5) kill 18884; process dosen't exit, repeated kill 18884 several times
6) kill -9 18884
7) ./semux-cli.sh; starts up starts syncing blocks

**Comment by Messier81z** [comment]
No problem, hope it's the same root cause as in #585.
