### ISSUE TITLE
1.0.1 ipfilter.json Parsing Error

### ISSUE THREAD

**Issue by iiqqrs** [semuxproject/semux#701]
#### System information

Semux version: v1.0.1

OS & Version: Windows 10

#### Expected behavior

>Install microsoft redistributable 2012
>Install java 8
> run semux.exe, create new account and semux begins connecting to peers and syncing.

#### Actual behaviour

After installing java 8 and the 2012 redistributable, running semux shows the new account creation screen. As soon as the wallet.data is created and in the same directory, the error I see every time I load up semux is:

<img>https://i.imgur.com/LeYlYOv.png</img>  

#### Steps to reproduce the behaviour

1. Download semux 1.0.1 on windows 10. 
2. Install dependencies
3. Run semux

#### Backtrace

````
2018-03-06T18:46:01-0500 ERROR    Wallet           Failed to decrypt the wallet data
2018-03-06T18:46:04-0500 INFO     Kernel           Semux/v1.0.1-27d00eb/Windows/amd64
2018-03-06T18:46:04-0500 INFO     Kernel           System booting up: network = mainnet, networkVersion = 0, coinbase = bcf549a6b732d89c55a7b550850cc6ade41c298a
2018-03-06T18:46:04-0500 INFO     Kernel           Computer: manufacturer = HP, model = HP ENVY Notebook
2018-03-06T18:46:04-0500 INFO     Kernel           OS: name = Microsoft Windows 10 (Home) build 16299
2018-03-06T18:46:04-0500 INFO     Kernel           CPU: processor = Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, cores = 4 / 8
2018-03-06T18:46:04-0500 INFO     Kernel           Memory: total = 12210 MB, available = 8454 MB, swap total = 1856 MB, swap available = 1856 MB
2018-03-06T18:46:04-0500 INFO     Kernel           Disk: name = \\.\PHYSICALDRIVE0, size = 244191 MB
2018-03-06T18:46:05-0500 INFO     Kernel           Network: name = Teredo Tunneling Pseudo-Interface, ip = []
2018-03-06T18:46:05-0500 INFO     Kernel           Network: name = Realtek PCIe GBE Family Controller, ip = []
2018-03-06T18:46:05-0500 INFO     Kernel           Network: name = Microsoft Wi-Fi Direct Virtual Adapter, ip = []
2018-03-06T18:46:05-0500 INFO     Kernel           Network: name = Bluetooth Device (Personal Area Network), ip = []
2018-03-06T18:46:05-0500 INFO     Kernel           Network: name = Intel(R) Dual Band Wireless-AC 3165, ip = [10.88.11.134]
2018-03-06T18:46:05-0500 INFO     Kernel           Java: version = 1.8.0_161, xmx = 6110 MB
2018-03-06T18:46:05-0500 INFO     Kernel           Latest block number = 0
2018-03-06T18:46:05-0500 INFO     PeerClient       Use IP address: 127.0.0.1
2018-03-06T18:46:05-0500 INFO     PeerClient       Starting IP refresh thread
2018-03-06T18:46:05-0500 INFO     PeerClient       New IP address detected: 127.0.0.1 => 199.253.243.20
2018-03-06T18:46:06-0500 ERROR    SemuxGui         Uncaught exception during kernel startup.
org.semux.net.filter.exception.ParseException: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (File); line: 1, column: 2]
	at org.semux.net.filter.SemuxIpFilter$Loader.load(SemuxIpFilter.java:248) ~[semux.exe:27d00eb]
	at org.semux.net.ChannelManager.<init>(ChannelManager.java:42) ~[semux.exe:27d00eb]
	at org.semux.Kernel.start(Kernel.java:136) ~[semux.exe:27d00eb]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:266) ~[semux.exe:27d00eb]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:240) [semux.exe:27d00eb]
	at org.semux.gui.SemuxGui.showUnlock(SemuxGui.java:205) [semux.exe:27d00eb]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:169) [semux.exe:27d00eb]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:86) [semux.exe:27d00eb]
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (File); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[semux.exe:27d00eb]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663) ~[semux.exe:27d00eb]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:614) ~[semux.exe:27d00eb]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2350) ~[semux.exe:27d00eb]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:646) ~[semux.exe:27d00eb]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4129) ~[semux.exe:27d00eb]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988) ~[semux.exe:27d00eb]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890) ~[semux.exe:27d00eb]
	at org.semux.net.filter.SemuxIpFilter$Loader.load(SemuxIpFilter.java:242) ~[semux.exe:27d00eb]
	... 7 more

[backtrace]
````
Address for bug bounty: 0x07e10a35db84a9392200e359e4e66e253156b2ee

**Comment by cryptokat** [comment]
@iiqqrs 
Could you upload your `config/ipfilter.json` here?
It must be a valid JSON file.

**Comment by iiqqrs** [comment]
The file contains:
```
{
  "rules": [
  ]
}
```
Github will not allow me to upload such file.

**Comment by cryptokat** [comment]
@iiqqrs Could you delete that file and try to open the wallet again?

**Comment by iiqqrs** [comment]
I've done exactly that and now I cannot reproduce the error anymore. I'm unsure what caused the issue as I surely didn't edit or modify that json file in any way. I'll be sure to re-open this issue if it happens again.

**Comment by cryptokat** [comment]
@iiqqrs Cool. Thanks for the update!
