### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" after locking wallet

### ISSUE THREAD

**Issue by Messier81z** [semuxproject/semux#907]
#### System information

Semux version: v1.2.0

OS & Version: Ubuntu 18.04

#### Expected behaviour

No exceptions thrown.

#### Actual behaviour

I locked my wallet via the GUI "Lock" button and noticed exceptions in the stderr.

#### Steps to reproduce the behaviour

1. Run the wallet & sync
2. Lock the wallet

#### Backtrace

Exception in thread "AWT-EventQueue-0" org.semux.core.exception.WalletLockedException: Wallet is locked  
        at org.semux.core.Wallet.requireUnlocked(Wallet.java:552)                                                           
        at org.semux.core.Wallet.getAddressAliases(Wallet.java:545)                                      
        at org.semux.gui.panel.SendPanel.refresh(SendPanel.java:340)                                     
        at org.semux.gui.panel.SendPanel.actionPerformed(SendPanel.java:289)                                                
        at org.semux.gui.model.WalletModel.lambda$updateView$2(WalletModel.java:340)                     
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)                
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)                                          
        at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)                               
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)                                                             
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)                                 
        at java.base/java.security.AccessController.doPrivileged(Native Method)                          
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)       
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)                           
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)                             
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by cryptokat** [comment]
This is not really a bug as the exception doesn't crash the wallet.

Way to reproduce:

1. Lock the GUI wallet
2. Attempt to unlock with a wrong password

**Comment by cryptokat** [comment]
@Messier81z 
It's just a kind of logging overhead. Some of the GUI components were trying to read the wallet while the wallet was already locked, thus the exception.

**Comment by Messier81z** [comment]
Thanks for explanation.
Sounds like a bug in some of the GUI components; ie. should they not try to check if (!wallet.locked) read();

to avoid throwing exceptions?

**Comment by orogvany** [comment]
It is logging noise, but as its continual, probably best we add check if locked and not update render in such cases

**Comment by Messier81z** [comment]
Great you've already fixed it in #908. Good job!

Can you please mark this as a bug so I can ask @semuxdev  for a bug bounty?
(my semux address is in my profile info)

Thanks

**Comment by cryptokat** [comment]
closed via #908
